services:
  streamlit_app:
    build: .
    depends_on:
      - qdrant
    ports:
      - "8501:8501"
    networks:
      - backend

  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    networks:
      - backend

networks:
  backend:
